apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jnbp1cd0c-go 
  janus-idp.io/tekton: jnbp1cd0c-go
  backstage.io/kubernetes-id: jnbp1cd0c-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jnbp1cd0c-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  